"""empty message

Revision ID: 90c42f445478
Revises: None
Create Date: 2016-11-29 22:26:11.074574

"""

# revision identifiers, used by Alembic.
revision = '90c42f445478'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('tag_id')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.INTEGER(), nullable=True))

    ### end Alembic commands ###
